server:
  # 端口及应用上下文路径
  port: 9001
  servlet:
    session:
      # session默认过期时间（应该用不到Session）
      timeout: PT60M
spring:
  application:
    name: hong-song
  # 设置当前项目运行环境
  profiles:
    active: test
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hongsong?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: jht123456
    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数大小，最小连接池数量，最大连接池数量
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 测试连接是否有效的sql
      validation-query: select 'x'
      # 建议配置为true，不影响性能，并且保证安全性
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      test-on-borrow: false
      # 配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
      test-on-return: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      # 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      # 监控统计用的filter:stat
      # 日志用的filter:log4j
      # 防御sql注入的filter:wall
      filters: stat,slf4j,wall
  mvc:
    path-match:
      # 修改默认请求路由匹配策略，以兼容Swagger接口文档
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis服务器连接密码（如果没有设置密码删除这一行）
    password: 123456
    # Redis数据库索引（默认为0）
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
# knife4j 配置
# 访问地址：http://ip:port/doc.html
knife4j:
  enable: true
  openapi:
    title: 洪松官方文档
    description: 洪松接口文档
    email: xxxxxxxx@qq.com
    concat: author
    url: www.baidu.com
    version: 1.0

# mybatis-plus设置
mybatis-plus:
  configuration:
    # mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 指定扫描mapper的路径
  mapper-locations: classpath*:/mapper/*.xml